name: 🔖 Release Tag

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 0'


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checking out the code
        uses: actions/checkout@v3

      - name: Create release and tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v6.1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Fetch Last Release Date
        id: last_release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release view  --json publishedAt --jq '.publishedAt' -R github.com/$GITHUB_REPOSITORY | xargs -I {} echo RDATE={} >> $GITHUB_OUTPUT

      - name: Count Available Commits
        id: available_commits
        run: |
          if ${{ steps.last_release.outputs.RDATE == '' }}
          then
              echo "Defaulting to 1 since this is a First Release"
              echo COUNT=1 >> $GITHUB_OUTPUT
          else 
              echo "Last Release was on ${{ steps.last_release.outputs.RDATE }} "
              git log --pretty=format:%an --since=${{ steps.last_release.outputs.RDATE }}  --oneline | wc -l | xargs -I {} echo COUNT={} >> $GITHUB_OUTPUT
          fi
            
      - name: Log Available Commits
        run: |
           echo Total Available Commits ${{ steps.available_commits.outputs.COUNT }}

      - name: Create a GitHub release
        if: ${{ steps.available_commits.outputs.COUNT > 0  }}
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.tag_version.outputs.new_tag }}
          release_name: Release ${{ steps.tag_version.outputs.new_tag }}
          body: ${{ steps.tag_version.outputs.changelog }}
